### ISSUE TITLE
Missing 'nonce' in the authorize request

### ISSUE THREAD

**Issue by azmeuk** [Worteks/yii2auth-oidc#3]
Hi
I have troubles making humhub work with [canaille](https://gitlab.com/yaal/canaille). I noticed that there is no `nonce` in the authorize request (and it is required by canaille).

```
/oauth/authorize?client_id=tvTlE86mOT1OeOnzLSVUhDGh&response_type=code&redirect_uri=https://humhub.foo.bar/index.php?r=user%2Fauth%2Fexternal&authclient=Foobar&xoauth_displayname=HumHub&scope=openid&state=79d4cb7d551ed074557c3b6b4445a98e9e1f1880dfdc66c4bbc44af5c697a4c4
```

Adding this piece of code to `OIDC.php` solves the issue, but I am not sure this is the right thing to do.

```php
    public function buildAuthUrl(array $params = [])
    {
        $nonce = parent::generateAuthNonce();
        $this->setState('authNonce', $nonce);
        $params['nonce'] = $nonce;
        return parent::buildAuthUrl($params);
    }
```

Is there a bug with yii2auth-oidc or did I miss some configuration somewhere?

Thank you for your help

**Comment by coudot** [comment]
> Hi
> I have troubles making humhub work with [canaille](https://gitlab.com/yaal/canaille). I noticed that there is no `nonce` in the authorize request (and it is required by canaille).

It should not be mandatory. See https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

```
nonce
    OPTIONAL. String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. Sufficient entropy MUST be present in the nonce values used to prevent attackers from guessing values. For implementation notes, see Section 15.5.2.

**Comment by azmeuk** [comment]
Thank you for the quick answer. Do you think it would be harmful to always provide a nonce, even if it is not strictly required by the specification?

**Comment by coudot** [comment]
It could indeed be an improvement. If we provide a nonce in authn request, we must check it when parsing the ID token.

**Comment by azmeuk** [comment]
Have you planed this feature or will it happen only if someone sends a patch for the feature?

**Comment by coudot** [comment]
This is not a top priority, of course if someone works on a patch, we will review it

**Comment by coudot** [comment]
Seems uii2-authclient now implements OIDC: https://github.com/yiisoft/yii2-authclient/blob/master/src/OpenIdConnect.php

@soisik maybe this project is no more needed anymore?

**Comment by azmeuk** [comment]
Actually, I ended using yii2-authclient.
